controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
captcha_route:
    path: /login
    controller: Gregwar\CaptchaBundle\Controller\CaptchaController::generateAction

app_verify_account:
    path: /verify-account
    controller: App\Controller\SecurityController::verifyEmail
    host: 195.110.59.49 # Replace 'example.com' with your actual domain name
    schemes: [http]
    methods: GET 

status_counts:
    path: /status_counts
    controller: App\Controller\MainController::getStatusCounts


# liste_users:
#   path: /listeUsers/{userId}
#   controller: App\Controller\MainController::getUserAction
#   methods: GET
